USE ACESSOCARD

CREATE TABLE TB_CONTATO(
	ID INT IDENTITY (1,1) PRIMARY KEY,
	NM_NOME VARCHAR(200) NOT NULL,
	DS_EMAIL VARCHAR(200) NOT NULL,
	DS_TELEFONE VARCHAR(20) NOT NULL,


)


CREATE TABLE TB_USER(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NM_NOME VARCHAR(200) NOT NULL,
	DS_EMAIL VARCHAR(200) NOT NULL,
	DS_SENHA VARCHAR(200) NOT NULL

)